//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharactersHdeleon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class character
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public character()
        {
            this.character1 = new HashSet<character>();
            this.character11 = new HashSet<character>();
        }
    
        public int id { get; set; }
        public int id_project { get; set; }
        public int id_state { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> id_father { get; set; }
        public Nullable<int> id_mother { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<character> character1 { get; set; }
        public virtual character character2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<character> character11 { get; set; }
        public virtual character character3 { get; set; }
        public virtual project project { get; set; }
        public virtual cstate cstate { get; set; }
    }
}
