//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharactersHdeleon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class characterhdeleonEntities : DbContext
    {
        public characterhdeleonEntities()
            : base("name=characterhdeleonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<character> character { get; set; }
        public virtual DbSet<cstate> cstate { get; set; }
        public virtual DbSet<location> location { get; set; }
        public virtual DbSet<project> project { get; set; }
    }
}
