//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharactersHdeleon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime created_date { get; set; }
        public int id_state { get; set; }
        public int id_project { get; set; }
    
        public virtual cstate cstate { get; set; }
        public virtual project project { get; set; }
    }
}
